#!/bin/zsh

session="${PWD:t}"

if tmux has-session -t "$session" 2>/dev/null; then
    if [[ -n "$TMUX" ]]; then
        tmux switch-client -t "$session"
    else
        tmux attach-session -t "$session"
    fi
    exit 0
fi

tmux new-session -d -s "$session" -c "$PWD"

tmux split-window -h -t "$session" -c "$PWD"
tmux split-window -v -t "$session" -c "$PWD"

tmux select-pane -t "$session"
tmux send-keys 'nvim .' Enter

if [[ -n "$TMUX" ]]; then
    tmux switch-client -t "$session"
else
    tmux attach-session -t "$session"
fi
