#!/bin/zsh

if [[ $# -ne 1 ]]; then
    echo "usage: feat <branch>"
    exit 1
fi

branch="$1"

if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    while git show-ref --verify --quiet "refs/heads/$branch" ||
          git show-ref --verify --quiet "refs/remotes/origin/$branch"; do

        echo "branch '$branch' already exists."

        branch="${branch}-"

        while true; do
            printf "new: "
            vared branch

            [[ -z "$branch" ]] && continue

            if git check-ref-format --branch "$branch" >/dev/null 2>&1; then
                break
            fi

            echo "invalid branch name."
        done
    done
else
    git init
fi

if tmux has-session -t "$branch" 2>/dev/null; then
    if [[ -n "$TMUX" ]]; then
        tmux switch-client -t "$branch"
    else
        tmux attach-session -t "$branch"
    fi
    exit
fi

if [[ -n "$TMUX" ]]; then
    tmux new-session -d -s "$branch" -c "$PWD"
    git switch -c "$branch"
    tmux switch-client -t "$branch"
else
    git switch -c "$branch"
    tmux new-session -s "$branch" -c "$PWD"
fi
